#!/bin/bash
doc="""
Launching jupyter for running python3 CliMAF and CESMEP notebooks on spirit with display on local browser
"""
modulep=${1:-MODULE_PATH}

set -e
USER=$( whoami )
myport=$( cat USER_PORTS | grep $USER | awk "-F " '{print $2 }' )

if netstat -at | grep -w $myport > /dev/null
then 
   echo "You already have a climaf-notebook running" 
   echo "only one per user could be running" 
   lsof|grep "$myport (LISTEN)" 
   exit 1
fi
SHORT_HOST="$(hostname -f)"
case $SHORT_HOST in
    spirit1.*|spirit2.*|spirit.*|spiritx.*)
	echo -e  "\033[1;31mPlease do not run this on login node $SHORT_HOST but use e.g.:\033[m"
	echo -e  "\033[1;34msrun --pty --mem-per-cpu=9G  --time=60 $0 \033[m"
	exit 1 ;;
   spirit*)
	SSH_TUNNEL="ssh -L ${myport}:${SHORT_HOST}:${myport} ${USER}@spirit1.ipsl.fr" 
	address= ;; 
    *) echo "Machine not handled" ; exit  ;; 
esac

echo
echo -e "\033[1;31m Launching the Jupyter notebook environment on the ESPRI cluster"
echo -e "\033[1;31m FIRST STEP: Open your port \033[m"
echo "     - open a terminal on your computer (!! NOT on Spirit, Ciclad, Loholt, Cerbere, Idefix... but on your local machine)"
echo "     - and connect to the Mesocenter with this blue command: "
echo -e "\033[1;34m $SSH_TUNNEL \033[m"
echo
echo -e "\033[1;31m And keep this terminal open until the end of your jupyter session. \033[m"
echo 


echo -e "\033[1;31m SECOND STEP: \033[m"
echo "    - among the url below (returned by Jupyter), choose the one with '127.0.0.1'"
echo "    - and paste in a browser on your computer (Chrome, Firefox...)"
echo
echo -e "\033[1;31m Have fun! \033[m"
echo
echo -e "\033[1;31m (wait until Jupyter returns the url... it might take some seconds...) \033[m"

module load $modulep

set -x
jupyter notebook --no-browser --port=${myport} --ip=0.0.0.0

